import { SocialAutomation, ActivityEvent, SocialLead, SocialChannel, Post, AiAutoPostConfig, AiSuggestedPost } from '../types';

export const INITIAL_AUTOMATIONS: SocialAutomation[] = [
  {
    id: 'flow-1',
    name: 'New DM Welcome',
    channel: 'instagram',
    trigger_type: 'dm_received',
    keywords: [],
    reply_comment: 'Hey there! Thanks for reaching out 👋',
    dm_message: 'Welcome to our page! Thanks for connecting. Check out our latest resources here: https://buffermate.ai/start',
    link_url: 'https://buffermate.ai/start',
    status: 'active',
    runs_today: 23,
    runs_total: 1847,
    leads_captured: 412,
  },
  {
    id: 'flow-2',
    name: 'Story Reply Follow-up',
    channel: 'instagram',
    trigger_type: 'story_reply',
    keywords: [],
    reply_comment: '',
    dm_message: 'Thanks for replying to our story! Here is the behind-the-scenes breakdown you asked for.',
    link_url: 'https://buffermate.ai/case-study',
    status: 'active',
    runs_today: 8,
    runs_total: 394,
    leads_captured: 89,
  },
  {
    id: 'flow-3',
    name: 'Keyword: Book',
    channel: 'instagram',
    trigger_type: 'comment_keyword',
    keywords: ['book', 'appointment', 'schedule', 'call', 'consult'],
    reply_comment: 'Just sent you a private DM with the calendar link! 📅 Check your inbox.',
    dm_message: 'Hey! Here is our VIP booking link to lock in your strategy call: https://buffermate.ai/book-vip',
    link_url: 'https://buffermate.ai/book-vip',
    status: 'active',
    runs_today: 5,
    runs_total: 212,
    leads_captured: 145,
  },
  {
    id: 'flow-4',
    name: 'Spam Filter & Hide',
    channel: 'instagram',
    trigger_type: 'spam_filter',
    keywords: ['spam', 'follow', 'fastfollow', 'crypto', 'dm me', 'check bio'],
    reply_comment: '',
    dm_message: '',
    status: 'active',
    runs_today: 0,
    runs_total: 56,
    leads_captured: 0,
  },
  {
    id: 'flow-5',
    name: 'TikTok Price & Discount DM',
    channel: 'tiktok',
    trigger_type: 'comment_keyword',
    keywords: ['price', 'cost', 'how much', 'discount', 'code', 'buy'],
    reply_comment: 'Check your TikTok DM! Sent you an exclusive 25% discount voucher 🎁',
    dm_message: 'Hey! You caught our secret TikTok deal. Use code TIKTOK25 at checkout: https://buffermate.ai/deal',
    link_url: 'https://buffermate.ai/deal',
    status: 'active',
    runs_today: 42,
    runs_total: 1204,
    leads_captured: 456,
  },
  {
    id: 'flow-6',
    name: 'Facebook Messenger Lead Bot',
    channel: 'facebook',
    trigger_type: 'comment_keyword',
    keywords: ['info', 'details', 'interested', 'send', 'guide'],
    reply_comment: 'Thanks for asking! I just sent the complete guide right to your Messenger 🚀',
    dm_message: 'Hi there! Here is the free 2026 Growth Playbook PDF: https://buffermate.ai/playbook.pdf',
    link_url: 'https://buffermate.ai/playbook.pdf',
    status: 'active',
    runs_today: 19,
    runs_total: 430,
    leads_captured: 178,
  },
  {
    id: 'flow-7',
    name: 'Threads Instant Link Drop',
    channel: 'threads',
    trigger_type: 'comment_keyword',
    keywords: ['link', 'source', 'tool', 'stack'],
    reply_comment: 'Sent you the full toolstack link in DM! ⚡️',
    dm_message: 'Hey! Here is the direct link to the automation stack: https://buffermate.ai/tools',
    link_url: 'https://buffermate.ai/tools',
    status: 'active',
    runs_today: 12,
    runs_total: 180,
    leads_captured: 64,
  },
  {
    id: 'flow-8',
    name: 'WhatsApp Business Auto-Responder',
    channel: 'whatsapp',
    trigger_type: 'dm_received',
    keywords: ['hello', 'hi', 'pricing', 'support'],
    reply_comment: '',
    dm_message: 'Hello! Thank you for contacting BufferMate support. A representative will be with you shortly or reply 1 for catalog.',
    link_url: 'https://buffermate.ai/support',
    status: 'active',
    runs_today: 15,
    runs_total: 320,
    leads_captured: 92,
  },
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-1',
    event_type: 'auto_dm',
    channel: 'instagram',
    title: 'Instagram DM Sent via Keyword Trigger',
    description: 'Auto-replied to @sophia_m on Reel "Branding Case Study" with discount link.',
    user_handle: '@sophia_m',
    post_reference: 'Reel: Branding Case Study',
    time_ago: 'just now',
    created_at: new Date().toISOString(),
  },
  {
    id: 'act-2',
    event_type: 'lead_captured',
    channel: 'tiktok',
    title: 'New Lead Captured on TikTok',
    description: 'Comment keyword "price" detected from @alex_creative, DM sent with checkout voucher.',
    user_handle: '@alex_creative',
    post_reference: 'TikTok: 3 AI Tools You Need',
    time_ago: '12m ago',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-3',
    event_type: 'comment_replied',
    channel: 'facebook',
    title: 'Facebook Post Comment Replied',
    description: 'Responded to @marcus_dev: "Check your inbox for the download link! 🚀"',
    user_handle: '@marcus_dev',
    post_reference: 'Post: Q3 Product Roadmap',
    time_ago: '34m ago',
    created_at: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-4',
    event_type: 'post_published',
    channel: 'threads',
    title: 'Threads Post Auto-Published',
    description: 'Auto-posted: "How we automated 100% of our customer DMs with AI in 3 simple steps."',
    post_reference: 'Threads Post #402',
    time_ago: '1h ago',
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-5',
    event_type: 'auto_dm',
    channel: 'instagram',
    title: 'Story Reply Welcome Sent',
    description: 'Auto-sent consultation booking link to @elena_marketing from Instagram Story.',
    user_handle: '@elena_marketing',
    post_reference: 'Story: Weekend Q&A',
    time_ago: '2h ago',
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-6',
    event_type: 'ai_autopost',
    channel: 'instagram',
    title: 'AI Auto-Pilot Published',
    description: 'Autonomous post created and published across Instagram & TikTok.',
    post_reference: 'AI Post: Peak Social Strategy',
    time_ago: '3h ago',
    created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_LEADS: SocialLead[] = [
  {
    id: 'lead-1',
    handle: '@sophia_m',
    name: 'Sophia Martinez',
    channel: 'instagram',
    keyword_triggered: 'book',
    status: 'new',
    last_interaction: 'just now',
    notes: 'Triggered calendar booking link from Instagram Reel comment',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    handle: '@alex_creative',
    name: 'Alex Rivera',
    channel: 'tiktok',
    keyword_triggered: 'price',
    status: 'qualified',
    last_interaction: '12m ago',
    notes: 'Requested 25% discount voucher on viral TikTok video',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-3',
    handle: '@marcus_dev',
    name: 'Marcus Chen',
    channel: 'facebook',
    keyword_triggered: 'guide',
    status: 'contacted',
    last_interaction: '34m ago',
    notes: 'Downloaded 2026 Growth Playbook PDF via Messenger',
    created_at: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-4',
    handle: '@david_growth',
    name: 'David Okafor',
    channel: 'threads',
    keyword_triggered: 'link',
    status: 'converted',
    last_interaction: '2h ago',
    notes: 'Subscribed to Pro Plan after receiving direct link in DM',
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    user_id: 'user-demo',
    channels: ['instagram', 'threads', 'facebook'],
    content: '🚀 Stop spending 5 hours a day replying to comments and DMs! Our AI automation detects keywords and delivers the link directly to their inbox in seconds.\n\nDrop "AUTOPILOT" below and we’ll DM you free early access! 👇\n\n#socialmediaautomation #marketingai #growthhacks #creatorbusiness',
    scheduled_at: new Date(Date.now() + 3600000 * 2).toISOString(),
    status: 'scheduled',
    attachments: [{ type: 'image', url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'post-2',
    user_id: 'user-demo',
    channels: ['tiktok', 'instagram'],
    content: '3 secret settings in your social media pipeline that 10x your conversion rate in 2026. Watch till the end for the automation blueprint! 💡\n\nComment "BLUEPRINT" to get the downloadable PDF.',
    scheduled_at: new Date(Date.now() + 3600000 * 6).toISOString(),
    status: 'scheduled',
    attachments: [{ type: 'video', thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80' }],
    created_at: new Date().toISOString(),
  },
  {
    id: 'post-3',
    user_id: 'user-demo',
    channels: ['facebook', 'threads'],
    content: 'Case Study: How we helped a boutique ecommerce brand generate $48,000 in additional sales using instant DM auto-funnels.\n\nFull breakdown inside the thread! 🧵',
    scheduled_at: new Date(Date.now() - 86400000).toISOString(),
    posted_at: new Date(Date.now() - 86400000).toISOString(),
    status: 'posted',
    attachments: [],
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_AI_SUGGESTIONS: AiSuggestedPost[] = [
  {
    id: 'sug-1',
    topic: 'Viral Comment-to-DM Growth Strategy',
    hook: 'How one simple comment automation generated 1,200 leads in 48 hours without spending $1 on ads 🤯',
    content: 'Most creators lose 80% of their post engagement because they cannot reply to comments fast enough.\n\nHere is the exact 3-step flywheel we use:\n1. Hook followers with a high-value resource\n2. Ask for a specific keyword comment (e.g. "ACCESS")\n3. Our AI engine instantly replies and DMs the link!\n\nComment "ACCESS" below to test this live right now! 👇\n\n#socialautomation #marketinghacks #leadgeneration #contentcreator',
    hashtags: ['#socialautomation', '#marketinghacks', '#leadgeneration', '#contentcreator', '#aiworkflows'],
    recommended_time: 'Today at 6:30 PM (Peak Reach Window)',
    target_channels: ['instagram', 'threads', 'facebook'],
    call_to_action: 'Comment "ACCESS" to get the playbook DM\'d instantly.',
    estimated_engagement: '94% Viral Potential',
  },
  {
    id: 'sug-2',
    topic: 'Automated 24/7 Social Funnels',
    hook: 'Why smart brands never leave customer DMs unread in 2026 📈',
    content: 'Speed to lead is everything. If a follower asks for pricing or product info, replying in 2 minutes vs 2 hours makes a 391% difference in conversion.\n\nAutomate your responses across Instagram, TikTok, and WhatsApp with zero code.\n\nDrop "DEMO" below for a private walkthrough!',
    hashtags: ['#growthmindset', '#businesstips', '#marketingstrategy', '#entrepreneurship'],
    recommended_time: 'Tomorrow at 9:00 AM (Morning Catch-up)',
    target_channels: ['tiktok', 'instagram', 'facebook'],
    call_to_action: 'Comment "DEMO" to test the auto-responder.',
    estimated_engagement: '88% High Conversion',
  },
  {
    id: 'sug-3',
    topic: 'Multi-Channel Publishing in 1-Click',
    hook: 'Stop posting manually to 5 different social networks one by one 🛑',
    content: 'Publishing everywhere doesn\'t mean working 10 hours a day.\n\nWith BufferMate AI, write once, optimize with AI per platform, and schedule in 30 seconds.\n\nCheck the link in our bio to try it free today!',
    hashtags: ['#productivitytips', '#socialmediamarketing', '#buffersocial', '#digitalmarketing'],
    recommended_time: 'Thursday at 1:15 PM (Lunchtime Surge)',
    target_channels: ['threads', 'facebook', 'whatsapp', 'instagram'],
    call_to_action: 'Click link in bio or drop "START" for instant onboarding.',
    estimated_engagement: '91% High Save Rate',
  },
];
